services:
  app:
    #    platform: linux/amd64
    build: .

    tty: true
    ports:
      - "80:80"
    volumes:
      - ./:/usr/src/app
    command: >
      bash -c "npm install &&
      node index.js"
  client:
    image: nginx
    ports:
      - 8000:80
